language: cpp
compiler:
  - gcc
  - clang
script:
  - ./configure
  - make test
before_install:
  - git submodule update --init --recursive
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
notifications:
  email:
    recipients:
      - z@apiary.io
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: "HqBUrmf4P2bgvwb4b9PL1tBae2wcZaXadOgwRwAFhdhDZFHaKXIXlJRUW8tN\ntdO83OZgatxJrpWWQj8VYTfDuhlE3b3NxVWeXc3PkfrHmuvejQf4veh7kwR0\njLVE6jb+ZbFIwRE2W0VFLFKYQHI6PLem4W0OKXW5Shqzy8Ewlow="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
env:
  - RVM=2.0.0
