version: 1.0.{build}

install:
  - git submodule update --init --recursive  

build_script:
  - vcbuild.bat MSVC2013
  
before_test:
  - gem install cucumber
  - gem install bundle

test_script:
  - vcbuild.bat MSVC2013 inttest

